<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1qSyxZh\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1qSyxZh/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container1qSyxZh.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container1qSyxZh\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container1qSyxZh\srcDevDebugProjectContainer(array(
    'container.build_hash' => '1qSyxZh',
    'container.build_id' => 'fbdf23ce',
    'container.build_time' => 1529334176,
), __DIR__.\DIRECTORY_SEPARATOR.'Container1qSyxZh');
